from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views
from django.conf.urls import url
from .views import *
urlpatterns = format_suffix_patterns([

    path('student/',
        views.StudentList.as_view(),
        name='student-list'),
    path('student/<int:pk>/',
         views.StudentDetail.as_view(),
         name='student-detail'),
    path('user_admin/',
        views.AdminList.as_view(),
        name='admin-list'),
    path('user_admin/<int:pk>/',
         views.AdminDetail.as_view(),
         name='admin-detail'),
    path('teacher/',
        views.TeacherList.as_view(),
        name='teacher-list'),
    path('teacherall/',
        views.TeacherListAll.as_view(),
        name='teacher-all-list'),
    path('teacher/<int:pk>/',
         views.TeacherDetail.as_view(),
         name='teacher-detail'),
    path('school/',
         views.SchoolList.as_view(),
         name='school-list'),
    path('school/<int:pk>/',
         views.SchoolDetail.as_view(),
         name='school-detail'),
    path('video/',
        views.VideoList.as_view(),
        name='video-list'),
    path('video/<int:pk>/',
         views.VideoDetail.as_view(),
         name='video-detail'),
    path('pptx/',
        views.PPTXList.as_view(),
        name='pptx-list'),
    path('pptx/<int:pk>/',
         views.PPTXDetail.as_view(),
         name='pptx-detail'),
    path('document/',
        views.DocList.as_view(),
        name='doc-list'),
    path('document/<int:pk>/',
         views.DocDetail.as_view(),
         name='doc-detail'),
    path('quiz/',
        views.QuizList.as_view(),
        name='quiz-list'),
    path('quiz/<int:pk>/',
         views.QuizDetail.as_view(),
         name='quiz-detail'),
    path('question/',
         views.QuestionList.as_view(),
         name='question-list'),
    path('question/<int:pk>/',
         views.QuestionDetail.as_view(),
         name='question-detail'),
    path('discussion/',
         views.DiscussionList.as_view(),
         name='discussion-list'),
    path('discussion/<int:pk>/',
         views.DiscussionDetail.as_view(),
         name='discussion-detail'),
    path('comment/',
         views.CommentList.as_view(),
         name='comment-list'),
    path('comment/<int:pk>/',
         views.CommentDetail.as_view(),
         name='comment-detail'),
    path('score/',
         views.ScoreList.as_view(),
         name='score-list'),
    path('score/<int:pk>',
         views.ScoreDetail.as_view(),
         name='score-detail'),
    path('quiz_score/<int:pk>',
         views.QuizScore.as_view(),
         name='quiz-score'),



    # path('coursetest/',
    #      views.CourseTestList.as_view(),
    #      name='coursetest-list'),
    # path('coursetest/<int:pk>/',
    #      views.CourseTestDetail.as_view(),
    #      name='coursetest-detail'),
    # path('testquestion/',
    #     views.TestQuestionList.as_view(),
    #     name='testquestion-list'),
    # path('testquestion/<int:pk>/',
    #      views.TestQuestionDetail.as_view(),
    #      name='testquestion-detail'),
    # path('examinee/',
    #     views.ExamineeList.as_view(),
    #     name='examinee-list'),
    # path('examinee/<int:pk>/',
    #      views.ExamineeDetail.as_view(),
    #      name='examinee-detail'),
    # path('enrollcourse/',
    #     views.CourseEnrollmentList.as_view(),
    #     name='courseenrollment-list'),
    # path('enrollcourse/<int:pk>/',
    #      views.CourseEnrollmentDetail.as_view(),
    #      name='courseenrollment-detail'),

    url(r'^api/auth/$', UserAuthentication.as_view(), name='User Authentication API'),
    # url(r'^upload/$', CourseMaterialView.as_view(), name='course_material-upload'),
])