# Generated by Django 3.1.7 on 2021-05-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
