# Generated by Django 3.1.7 on 2021-05-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0002_remove_schoolsection_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birth_date',
        ),
    ]
