# Generated by Django 3.1.7 on 2021-05-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0002_quiz_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.PositiveSmallIntegerField(choices=[(1, 'options_1'), (2, 'options_2'), (3, 'options_3'), (4, 'options_4')]),
        ),
    ]
