version: '3.9'
services:
  solarlms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8000:8000
    volumes:
    - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: myrel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - .dbdata:/var/lib/mysql
    ports:
    - 33073:3306

  dashboard:
    build: ../../Dashboard/Dockerfile
    container_name: frontend_c
    ports:
    - '3000:3000'
    stdin_open: true
    tty: true
  

